---
title: "TITLE"
author: "Ebony Hunt"
date: "2026-05-22"
output:
  pdf_document: 
    keep_tex: true
  html_document: default
header-includes:
  \usepackage{placeins}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyr)
library(dplyr)
library(tsibble)
library(feasts)
library(fable)
library(ggplot2)
library(forecast)
```

### GitHub Repository:

### <https://github.com/a1926113/Time_Series_Report>

# Abstract

# Introduction

# Methods

```{r read_data, warning=FALSE, show_col_types = FALSE, include=FALSE}
BirthsAndFertilityRatesAnnual <- 
  read_csv("C:/Users/ebony/OneDrive - University of Adelaide/Desktop/2026 Time Series/BirthsAndFertilityRatesAnnual (1).csv")
```

```{r to_double, include=FALSE}
BirthsAndFertilityRatesAnnual <- BirthsAndFertilityRatesAnnual |>
  mutate(across(2:67, as.character)) |>
  mutate(across(2:67, ~na_if(., "na"))) |>
  mutate(across(2:67, as.double))
```

```{r pivot_longer,warning=FALSE, include=FALSE}

BirthsAndFertilityRatesAnnual <- BirthsAndFertilityRatesAnnual |>
  pivot_longer(cols = -DataSeries,
               names_to = "Year",
               values_to = "Value") |>
  pivot_wider(names_from = DataSeries,
              values_from = "Value")

BirthsAndFertilityRatesAnnual$Year <-as.integer(BirthsAndFertilityRatesAnnual$"Year")

BirthsAndFertilityRatesAnnual <- BirthsAndFertilityRatesAnnual[, -c(3:15, 17,18)]
```

# Results

# Discussion

# Conclusion

# References